### ISSUE TITLE
TotM-Manager button has disappeared

### ISSUE THREAD

**Issue by Zackun** [LichFactory-Games/TotM-Manager#1]
Hello,
I installed the module and everything worked fine yesterday, but today the module doesn't work anymore.
The button that allows access to the manager in "Tile Controls" no longer appears.

I get this error message in the console: 
![TotmError](https://github.com/LichFactory-Games/TotM-Manager/assets/51156718/53a15b6a-2265-43d6-aa7d-f550e01ec010)

I tried on another computer and same problem.

Does anyone have any idea what's wrong?

**Comment by mclearc** [comment]
Have you tried disabling your other modules and just running totmm? And what version of foundry and system are you using?

**Comment by Zackun** [comment]
Yes, I tried disabling all other modules, creating new worlds and reinstalling foundry. But nothing worked.
I'm using version 11.315.

**Comment by mclearc** [comment]
> Yes, I tried disabling all other modules, creating new worlds and reinstalling foundry. But nothing worked. Edit: I'm using version 11.315 for foundry and 0.8.1 for TotM.

I haven't been able to reproduce this. I've trying with the most recent version of totmm (0.8.1) and the dependencies tagger (1.4.5), token magic (0.6.8), and lib wrapper (1.12.14). All on v.11 of foundry

**Comment by Zackun** [comment]
I've tried using the same versions for each module, but it didn't work.

**Comment by mclearc** [comment]
> I've tried using the same versions for each module, but it didn't work.

I haven't changed anything with the module in a week. I thought maybe one of the dependencies updated and caused an error, but that doesn't seem to be the case. I wish I could help more but so far I can't recreate the problem (and so can't test against it). 

If you get any further information as to what might have changed between the last use of totmm and this please let me know.

**Comment by Zackun** [comment]
I had no problems yesterday with v0.8.1 so this is really weird.

I tried with v0.6.8 and v.7.0 and they both work even though I have the error that is on the screenshot. 
The v0.8.0 and 0.8.1 still don't work.

Thank you for your time. If I find any more info I'll let you know.

**Comment by Zackun** [comment]
I managed to get TotM running in v0.8.1, by removing this part of the code (in hooks.js):

```
// Register keybinding from settings
  game.keybindings.register(moduleId, 'openManager', {
    name: 'Open/Close TotM Manager',
    hint: 'Toggles the Theatre of the Mind Manager window.',
    editable: [{ key: 'KeyT', modifiers: ['Control'] }], // Set default keybinding
    onDown: () => {
      console.log("TotM Manager: Keybinding triggered");

      // Check if the singleton instance is rendered
      if (TotMForm._instance && TotMForm._instance.rendered) {
        // If the instance is rendered, close it (hide it)
        TotMForm._instance.close();
      } else {
        // If the instance is not rendered, render it
        TotMForm.renderSingleton();
      }
      return true;
    },
    restricted: true
  });
```

**Comment by mclearc** [comment]
Yes -- though what I'm confused about is why that was necessary. But I'm glad you have something working and I'll see if I can better implement the key binding in the next version

**Comment by mclearc** [comment]
Hi @Zackun -- I've since updated the module so I'm curious if you still have trouble on the latest version (v0.8.3)?

**Comment by Zackun** [comment]
Hello, thank you for notifying me. Unfortunately the problem is still there in v0.8.3.
![Totm](https://github.com/user-attachments/assets/ae27462c-bda8-46e0-9876-329c53f54851)

**Comment by mclearc** [comment]
Thanks @Zackun -- this is strange since the keybinding, as far as I can tell, **is** being called during, and not after, initialization. If you don't mind doing a bit of testing. One thing to try is simply reversing the order of the setupModule and initializeHooks calls in the *init.js* file in the totmm module directory. So replacing this:

```js 

Hooks.once('init', async function() {
  console.log("Theatre of the Mind Manager | Initializing module");
  await setupModule();
  initializeHooks();
});
```

With this:

```js

Hooks.once('init', async function() {
  console.log("Theatre of the Mind Manager | Initializing module");
  initializeHooks();
  await setupModule();
});
```

**Comment by Zackun** [comment]
It worked, the problem is solved. Thanks a lot!
