### ISSUE TITLE
Module.json is not accessible via link in module description (at least,  not from the Forge)

### ISSUE THREAD

**Issue by franckflo** [LichFactory-Games/TotM-Manager#11]
Hello, that concept seems really neat and I hope you’ll keep improving this module. Thanks!

I noticed that copy pasting the link to the module.json in the description of your module into the Forge « install via manifest » link is not working.

**Comment by mclearc** [comment]
Thanks! I'm not sure what the issue is with the Forge. I know that they need to update their package listings every day, so perhaps it's a problem stemming from that -- if so I expect it would clear up by their next update. But otherwise I'm relatively unfamiliar with how the Forge works.

**Comment by franckflo** [comment]
That makes two of us :). I was able to install your module from the latest release, looking forward to using it for my narrative scenes. Thanks!
