### ISSUE TITLE
Feature Request: WebM support and S3 Storage

### ISSUE THREAD

**Issue by linusboyle** [LichFactory-Games/TotM-Manager#12]
Hi, I want to thank you for this brilliant module, as it saves me tons of time.

While using TotM Manager I notice that I cannot select video files in the filepicker. Besides, I store my images on a S3 Storage, but currently TotM does not support bulk import from a remote folder. I really hope you could add these QoL improvement.

**Comment by mclearc** [comment]
See the [latest release](https://github.com/LichFactory-Games/TotM-Manager/releases/tag/v0.8.7). This should fix all your issues, though I haven't tested the S3 downloading. Feel free to reopen the issue if you're still seeing problems.
