### ISSUE TITLE
Feature Request: Force aspect ratio of tile when image changes

### ISSUE THREAD

**Issue by loofou** [LichFactory-Games/TotM-Manager#13]
Hey,

First of all thanks for this great module. It help a lot in creating dynamic TotM scenes, but also scenes like landing pages, etc.

Unfortunately most of my scene or npc images have different aspect ratios, so they always appear squished one way or another when setting the tiles. It would be incredibly helpful if there was an option to resize a tile to fit the aspect ratio of the new selected image. I think the cleanest option is to set this on each tile. It should be adjustable if you want the width or the height to change of the tile.

Then whenever you select a new image, after the fadeout, the tile size should be adjusted accordingly before the new image is faded in.

Thanks,
Loofou

**Comment by mclearc** [comment]
Thanks -- I'll look in to this. Generally I've tried to stay away from affecting the existence or properties of canvas objects (other than things like added effects), but I agree that this would be a useful feature to have.
