### ISSUE TITLE
lacks permission error

### ISSUE THREAD

**Issue by rlavkvmflzk** [LichFactory-Games/TotM-Manager#14]
![1728508768115](https://github.com/user-attachments/assets/2908be83-34aa-46da-9101-da7085af0c59)
I am using the module really well. Thanks for making the module. 

However, with the module enabled, when the GM creates a tile, the player gets a lack of permission error as shown in the screenshot.
I am using two foundry versions, 12.331 and 11.315, and both versions generate the same error.  The problem occurs even if only this module and its dependencies are turned on.

**Comment by mclearc** [comment]
thanks very much! can you say more about how the error occurs? I can create new tiles without seeing this problem. Can you tell me whether you're using the latest version of TotM Manager, and what version of foundry you're using?

**Comment by rlavkvmflzk** [comment]
I'm using foundry versions 12.331 and 11.315. Totm Manager is using version 0.8.66. I play a game that uses a lot of tiles, so my players seem to get a lot of error messages whenever a tile is created. I'm using a world script to prevent the messages from appearing, but it's pretty frustrating for the players if I don't use it

**Comment by mclearc** [comment]
I think I've resolved all the permissions problems (turns out this is a pretty common issue raised in the foundry discord) -- please let me know if the latest release is still giving your players trouble
