### ISSUE TITLE
What is TokenMagic module?

### ISSUE THREAD

**Issue by Vesselchuck** [LichFactory-Games/TotM-Manager#2]
I don't get it why the module doesn't work without some unknown to Foundry VTT module. It can't even be installed. Could that be fixed?

**Comment by mclearc** [comment]
I'm not quite sure I understand your question. Token Magic is required to make effects on tiles work with totmm. You can find out more about it here: https://github.com/Feu-Secret/Tokenmagic

**Comment by Vesselchuck** [comment]
Okay, It seems that the module in question is not named "Tokenmagic" after all. That was the reason you can't find it in Foundry VTT module list.

**Comment by Vesselchuck** [comment]
I've tried "Token Magic FX" and still get zero results, unfortunately.

**Comment by Vesselchuck** [comment]
Only those come up in search:
![image](https://github.com/user-attachments/assets/36d964db-98fc-44b8-9eb4-906d374c604d)

**Comment by Vesselchuck** [comment]
Does this module have to be installed manually?
