### ISSUE TITLE
Tile's effects cannot be viewer, or removed, but can be applied when scene is not active.

### ISSUE THREAD

**Issue by 4m2c4bl3** [LichFactory-Games/TotM-Manager#3]
After adding an effect to a tile when the scene is not active, I start receiving these issues. I also do not see the effect in the list. I have to switch to that scene being active to see and remove the effect.
![image](https://github.com/user-attachments/assets/7bd320b3-6ff9-4f27-b0ed-9e11e9501b2d)
Using Foundry V12.330 on chrome

**Comment by mclearc** [comment]
Thanks for the report! Unfortunately I haven't yet updated TotM for foundry v. 12. I believe that token magic is not yet fully compatible with v.12 either and apparently is no longer maintained (the community is trying to update it but progress has been slow). I'll take a look at this though when I update to v.12

**Comment by mclearc** [comment]
Hi @4m2c4bl3  I've updated TotMM for compatibility with v.12. You need to use TokenMagic 0.6.8, though there still seem to be problems for at least some people. Unfortunately there isn't much I can do about this on my end. Let me know if this resolves your problem.

**Comment by 4m2c4bl3** [comment]
seems to be working perfectly in the first test. thanks :)
