### ISSUE TITLE
Suggestion: Loop ending after specific amount of repeats

### ISSUE THREAD

**Issue by Akallabeth13666** [LichFactory-Games/TotM-Manager#4]
Hi,

Unless I do not understand how to use this tool properly I would like to suggest adding an option where it can be specified that the effect attached to a specific tile or picture ends after some time or a particular amount of repeats.

That would vastly improve the capabilities of this tool.
For instance, I like the bloom effect but I would like it to show up only once upon transition to the new tile or image.

**Comment by mclearc** [comment]
You can already do this when you set up a tile effect. In the JSON that appears when you select a specific effect from the dropdown, one of the fields will be "loop duration" -- change that to you preferred value. For more see the TokenMagic README here: https://github.com/Feu-Secret/Tokenmagic#token-magic-api

**Comment by Akallabeth13666** [comment]
It was actually "loops" not loop duration. However, it is still not perfect because the effect may stop in the middle instead of running one full loop:

![image](https://github.com/user-attachments/assets/21148bb8-3bc1-4107-abee-3357d0290072)

![image](https://github.com/user-attachments/assets/fdb3728e-9b6a-47df-ae05-b37f776bd90a)

**Comment by mclearc** [comment]
Here's the relevant part from the README: 

> TotM Manager can also attach specific playlists or macros to images so long as you have their respective IDs. In the image tags field you can add playlists by using the tag 'play-ID' and call a macro using the tag 'macro-ID'. This allows you to, for example, have images where the lights do a flicker effect while a thunder playlist plays.

> Note that the scene must be active for lights and related effects to trigger by image.
