### ISSUE TITLE
Image Transition Effect

### ISSUE THREAD

**Issue by eldwind** [LichFactory-Games/TotM-Manager#8]
Hello Firstly thanks for your great job

I have a problem with the image transition effect, i have token magic effect 0.6.8 installed but i have no effect in the list (see screenshot below).
I have test on a fresh world with different system (starwars FFG, DnD 5e) same problem
thank you

Edit: i'm on Foundry V12.331 (tested with v12.330 same problem) and the effect works on tiles the problem is only for transition

<img width="579" alt="chrome_7MB8UJYpG8" src="https://github.com/user-attachments/assets/00149188-3867-4543-aa8d-6f5ed5798671">

**Comment by mclearc** [comment]
Thanks! Yes I've been seeing this too -- will fix it this week if I can (it may be an issue with token magic in v12 -- there are fixes for that coming, but it's been slow going)

**Comment by eldwind** [comment]
ok thanks !

**Comment by mclearc** [comment]
See [the latest release](https://github.com/LichFactory-Games/TotM-Manager/releases/tag/v0.8.6)
